# Prototype of a possible IASI structured -> HTML preparation step.
# Source files under chapters/ are read-only. Derived artifacts are written
# to generated/parts/ and _generated-sidebar.yml.

root = normalizePath(".", winslash = "/", mustWork = TRUE)
chapters_dir = file.path(root, "chapters")
generated_dir = file.path(root, "generated", "parts")
dir.create(generated_dir, recursive = TRUE, showWarnings = FALSE)

read_qmd = function(path) {
  readLines(path, warn = FALSE, encoding = "UTF-8")
}

split_front_matter = function(lines) {
  if (!length(lines) || trimws(lines[[1]]) != "---") {
    return(list(front = character(), body = lines))
  }

  endings = which(trimws(lines) == "---")
  if (length(endings) < 2L) {
    stop("Front matter not closed.", call. = FALSE)
  }

  end = endings[[2]]
  front = if (end > 2L) lines[2:(end - 1L)] else character()
  body = if (end < length(lines)) lines[(end + 1L):length(lines)] else character()
  list(front = front, body = body)
}

front_title = function(front, fallback) {
  match = grep("^title\\s*:", front, value = TRUE)
  if (!length(match)) return(fallback)

  value = sub("^title\\s*:\\s*", "", match[[1]])
  value = sub('^"(.*)"$', "\\1", value)
  value = sub("^'(.*)'$", "\\1", value)
  value
}

demote_headings = function(lines) {
  sub("^(#{1,5})([[:space:]])", "#\\1\\2", lines, perl = TRUE)
}

quote_yaml = function(value) {
  value = gsub('"', '\\\\"', value, fixed = TRUE)
  sprintf('"%s"', value)
}

folders = list.dirs(chapters_dir, recursive = FALSE, full.names = TRUE)
folders = sort(folders)

sidebar = c(
  "website:",
  "  sidebar:",
  "    style: floating",
  "    collapse-level: 1",
  "    contents:",
  "      - text: \"Inicio\"",
  "        href: index.qmd"
)

for (folder in folders) {
  folder_name = basename(folder)
  part_index = file.path(folder, "index.qmd")
  if (!file.exists(part_index)) next

  part = split_front_matter(read_qmd(part_index))
  part_title = front_title(part$front, folder_name)

  documents = list.files(folder, pattern = "\\.qmd$", full.names = TRUE)
  documents = sort(documents[basename(documents) != "index.qmd"])
  if (!length(documents)) next

  generated_relative = file.path("generated", "parts", paste0(folder_name, ".qmd"))
  generated_path = file.path(root, generated_relative)

  page = c(
    "---",
    sprintf("title: %s", quote_yaml(part_title)),
    "number-sections: true",
    "---",
    "",
    "<!-- Generated by scripts/prepare.R. Do not edit. -->",
    ""
  )

  if (length(part$body)) {
    page = c(page, part$body, "")
  }

  sidebar = c(
    sidebar,
    sprintf("      - section: %s", quote_yaml(part_title)),
    "        contents:"
  )

  chapter_number = 0L

  for (document in documents) {
    chapter_number = chapter_number + 1L
    parsed = split_front_matter(read_qmd(document))
    stem = tools::file_path_sans_ext(basename(document))
    title = front_title(parsed$front, stem)
    anchor = paste0("chap-", stem)

    page = c(
      page,
      sprintf("# %s {#%s}", title, anchor),
      "",
      demote_headings(parsed$body),
      ""
    )

    href = paste0(gsub("\\\\", "/", generated_relative), "#", anchor)
    sidebar = c(
      sidebar,
      sprintf("          - text: %s", quote_yaml(sprintf("%d %s", chapter_number, title))),
      sprintf("            href: %s", href)
    )
  }

  writeLines(page, generated_path, useBytes = TRUE)
}

writeLines(sidebar, file.path(root, "_generated-sidebar.yml"), useBytes = TRUE)

cat("IASI structured numbering prototype prepared.\n")
cat(sprintf("Parts: %d\n", length(folders)))
cat("Render with Quarto or use RStudio Render Website.\n")
