project:
  output-dir: _outputs/html

website:
  announcement:
     content: |
        ![](/resources/images/ants.png){.iasi-ants-image}
     position: above-navbar
     dismissable: false

book:
  sidebar:
    collapse-level: 1
    
  page-footer:
    left: "© 2026 Javier G. Grandez · IASI Rocks 🤘"
    center: '<span id="iasi-publish-date"></span>'
    right: "Licencias"
    
  navbar:
    title: "IASI Structured"
    background: primary
    pinned: true

    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Parte I"
        href: chapters/10-first-part/index.qmd
      - text: "Parte II"
        href: chapters/20-second-part/index.qmd

    right:
      - icon: download 
        text: "Guardar ..."
        menu: 
           - text: "Guardar ..."
             href: "#iasi-exports"    
      - icon: box-arrow-up-right
        href: "#iasi-open-external"
        aria-label: "Abrir en una pestaña nueva"
        
  search:
    location: navbar
    type: overlay

format:
  html:
    pagetitle: "IASI Vol. I"
    title-prefix: ""
    include-in-header:
      text: '<script src="resources/js/iasi.js"></script>'
    theme: 
      - cosmo
      - resources/css/iasi.scss
      - resources/css/book.scss
    toc: true
